services:
  app:
    build: .
    image: node:alpine
    container_name: node-app
    working_dir: /usr/app
    volumes:
      - .:/usr/app
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=DEV
      - DATABASE_URL=${DATABASE_URL}
    command: npm run dev

  postgresql:
    image: postgres
    container_name: database
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${DATASOURCE_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
