-- AlterTable
ALTER TABLE "List" ADD COLUMN     "releaseDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "TaskList" ADD COLUMN     "weight" INTEGER NOT NULL DEFAULT 1;
